[build]
  functions = "netlify-functions"
  publish = ".next"
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirect]]
  from = "/"
  to = "/geography"
  status = 301
  force = true
